[package]
name = "mix-distribution"
version = "0.1.0"
authors = ["Hidehito Yabuuchi <hdht.ybuc@gmail.com>"]

description = "Mixture distribution"

documentation = "https://docs.rs/mix-distribution"
homepage = "https://crates.io/crates/mix-distribution"
repository = "https://github.com/ordovicia/mix-distribution"
readme = "README.md"

keywords = ["random"]
# categories = []

license-file = "LICENSE"

[badges]
travis-ci = { repository = "ordovicia/mix-distribution" }

[dependencies]
rand = "0.6.0-pre.0"
